
# dataset info
dataset_name: "EUVP"
dataset_path: "/home/cbel/Desktop/Sadie/FUnIE-GAN-master/EUVP/Paired/"


# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 100 # steps org 1000
ckpt_interval: 10  # 20 epochs save a model



 
